.TH "away_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
away_case \- \fBaway_case\fP 
Deja un mensaje explicando que en ese momento no estamos prestando atención\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBaway_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBmsg\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Deja\fP un\fP mensaje\fP explicando que en ese momento no estamos prestando atención\&.
.PP
Recibe como parámetros el prefijo que nos da la funcion de parseo del comando,el mensaje de que explica que ese momento no estamos prestando atención, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "VER TAMBIÉN"
.PP
\fB\fP 
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
