.TH "do_daemon" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
do_daemon \- \fBdo_daemon\fP 
Genera un demonio\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<connectServer\&.h>\fP 
.PP
\fBint\fP \fBdo_daemon\fP \fB\fP(\fBchar\fB*\fBidentificador\fB\fP)\fP  \fP \fP descripcion DESCRIPCIÓN
.PP
Genera un demonio para correr la aplicación en segundo plano\&.
.PP
Recibe como parámetro un identificador que es el nombre del servidor\&.
.SH "RETORNO"
.PP
0: si todo es correcto\&. -1: en caso de error\&.
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
