.TH "kick_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kick_case \- \fBkick_case\fP 
Expulsa al usuario que le indiquemos del canal especificado\&. Opcionalmente añade un comentario\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBkick_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBchannel\fB\fP,\fP \fBchar\fB*\fBuser\fB\fP,\fP \fBchar\fB*\fBcomment\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Expulsa\fP al\fP usuario\fP que\fP le\fP indiquemos\fP del\fP canal especificado\&. Opcionalmente añade un comentario\&.
.PP
Recibe como parámetros el prefijo que nos da la funcion de parseo del comando,el canal para expulsar al usuario, el usuario que deseamos expulsar, el mensaje que explica el motivo de la expulsión, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "VER TAMBIÉN"
.PP
\fB\fP 
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
