.TH "mode_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mode_case \- \fBmode_case\fP 
Modifica el modo del canal
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBmode_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBchannel\fB\fP,\fBchar\fB*\fBmode\fB\fP,\fP \fBchar\fB*\fBuser\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Modifica\fP el\fP modo\fP del\fP canal\fP si\fP este\fP se\fP especifica, en caso contrario indica el modo del canal\&.
.PP
Recibe como parámetros el prefijo que nos da la funcion de parseo del comando,el canal sobre el cual se ejecuta el modo, el modo del canal, el usuario que solicita el cambio, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "VER TAMBIÉN"
.PP
\fB\fP 
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
