.TH "motd_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motd_case \- \fBmotd_case\fP 
Envia un mensaje de comando desconocido\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBunknown_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBtarget\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Envia\fP un\fP mensaje\fP de comando desconocido al cliente que introduce el comando\&.
.PP
Recibe como parámetros el prefijo que nos da la funcion de parseo del comando,el target, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "VER TAMBIÉN"
.PP
\fB\fP 
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
