.TH "names_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
names_case \- \fBnames_case\fP 
Muestra una lista con todos los usuarios de un canal\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<IRCcommands\&.h>\fP 
.PP
\fBvoid\fP \fBnames_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBchannel\fB\fP,\fP \fBchar\fB*\fBtarget\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Muestra\fP una\fP lista\fP con\fP todos\fP los usuarios de un canal\&. Tambien se puede especificar el servidor\&.
.PP
Recibe como parámetros el prefijo que nos da la funcion de parseo del comando, el canal sobre el cual queremos la información, target nos indica un servidor especifico para solicitar la información, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
