.TH "user_case" 3 "Sun May 1 2016" "Conexion SSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_case \- \fBuser_case\fP 
Añade un usuario al TAD de usuarios\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<IRCcommands\&.h>\fP 
.PP
\fBvoid\fP \fBuser_case\fP \fB\fP(\fBchar\fB*\fBprefix\fB\fP,\fP \fBchar\fB*\fBusername\fB\fP,\fP \fBchar\fB*\fBhostname\fB\fP,\fP \fBchar\fB*\fBservername\fB\fP,\fP \fBchar\fB*\fBrealname\fB\fP,\fP \fBchar\fB**\fBnick\fB\fP,\fP const\fBint\fBsd\fB\fP)\fP  \fP \fP descripcion\fP DESCRIPCIÓN\fP  Añade\fP un\fP usuario\fP al\fP TAD\fP de\fP usuarios\fP\&.\fP  Recibe\fP como parámetros el prefijo que nos da la funcion de parseo del comando, el nombre del usuario, nombre del host, nombre del servidor, nombre real, el nick del usuario que envia el mensaje y su socket correspondiente\&.
.SH "RETORNO"
.PP
No devuelve nada\&.
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
